---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    region: us-east-1
  tasks:  
    - name: launch instance
      local_action:  
        module: ec2  
        region: "{{ region }}"  
        key_name: cf
        instance_type: t2.micro  
        image: ami-fce3c696
        wait: yes    
        group: sg_cf
      register: ec2  
    - name: associate new EIP for the instance    
      local_action:  
        module: ec2_eip 
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
