---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: us-east-1a
  tasks:  
    - name: EC2 basic provisioning  
      local_action:  
        module: ec2  
        region: "{{ region }}"  
        key_name: cf3
        instance_type: t2.micro  
        image: 	ami-fce3c696  
        wait: yes    
        group: sg_cf
        instance_tags:  
          group: webserver  
        exact_count: 1  
        count_tag:  
          group: webserver
